services:
  vila_bot:
    build:
      context: .
    container_name: vila_bot
    command: ["index.ts"]
    pull_policy: build
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
    restart: always

  redis:
    image: redis:latest
    restart: always
    ports:
        - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
        test: ['CMD', 'redis-cli', 'ping']
        interval: 10s
        timeout: 5s
        retries: 3
    volumes:
        - cache-data:/var/lib/redis
volumes:
  cache-data: {}
